### ISSUE TITLE
Documentation link leads to a 404

### ISSUE THREAD

**Issue by imaustink** [DanielCordell/TextEverything#2]
The [document link](http://texteverything.net/docs) in the readme leads to a 404 error page.

**Comment by DanielCordell** [comment]
Hi!

Yeah we've know about this for a bit. We did a server migration and lost the docs. We'll get new ones up as soon as possible!

**Comment by monotron** [comment]
Hello there, sorry for the inconvenience. I'll report back when the docs are back up!

**Comment by monotron** [comment]
Sorry to revive this issue from the dead. Since we no longer own the domain on which the docs were hosted, I'm going to close this issue until we figure out a solution to this
