### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by monotron** [DanielCordell/TextEverything#5]
Our package.json hasn't been updated in almost a year, and as a result our dependencies are out of date, potentially with security vulnerabilities. These all need updating to the latest versions, and the application needs testing and/or updating to make sure it works with the new versions.

**Comment by mikalai-sokarau** [comment]
Hello, I'll help with updating, please assign to me :)

**Comment by monotron** [comment]
@mikalai-sokarau sorry, you were beaten to it :( thanks for offering to contribute though!
